version: '3'
services:
  spring-server:
    restart: always
    image: spring-server-image
    ports:
      - "8083:8083"
    depends_on:
      - mongoDb
    build: .
    command: sh -c "sleep 5 && java -jar ./build/libs/2023b.shir.zur2-1.0.0-FINAL_SPRINT.jar"
    links:
      - mongoDb
    environment:
      DBCONTAINERNAME: mongoDb
  mongoDb:
    container_name: mongoDb 
    restart: always
    image: mongo
    ports:
      - "27017:27017"

